[package]
name = "building-your-own-shell-using-rust"
version = "0.1.0"
authors = ["'leftyant' <404ari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
